import "../styles/global.css";
import { Metadata } from "next";
import Navigation from "../components/navigation"

// export const metadata = {
//   title: 'Next.js Movies',
//   description: 'Generated by Next.js',
// }

export const metadata : Metadata = {
  title: {
    template: "%s | Next Movies",
    default: "Next Movies",
  },
  description: 'Study Next js Movies Project',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
        </body>
    </html>
  )
}
